---
apiVersion: v1
kind: Service
metadata:
  name: springboot-petclinic
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: springboot-petclinic

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-petclinic
  labels:
    app: springboot-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-petclinic
  template:
    metadata:
      labels:
        app: springboot-petclinic
    spec:
      containers:
        - name: workload
          image: prayags/springboot-petclinic:v2
          #image: dsyer/springboot-petclinic
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: postgres
            - name: SERVICE_BINDING_ROOT
              value: /bindings
            - name: SPRING_APPLICATION_JSON
              value: |
                {
                  "management.endpoint.health.probes.add-additional-paths": true
                }
            - name: POSTGRES_URL
              value: jdbc:postgresql://postgres-db:5432/petclinic
            - name: POSTGRES_USER
              value: petclinic
            - name: POSTGRES_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-db-secret
                  key: password
          ports:
            - name: http
              containerPort: 8080

